
services:
  web:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    container_name: dockerized_clubosphere
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/
    working_dir: /app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
